"""Add opcoes_sistema table

Revision ID: 012e17a40094
Revises: de3c51351108
Create Date: 2026-07-20 14:35:45.698692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012e17a40094'
down_revision: Union[str, Sequence[str], None] = 'de3c51351108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opcoes_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opcoes_sistema_category'), 'opcoes_sistema', ['category'], unique=False)
    op.create_index(op.f('ix_opcoes_sistema_id'), 'opcoes_sistema', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opcoes_sistema_id'), table_name='opcoes_sistema')
    op.drop_index(op.f('ix_opcoes_sistema_category'), table_name='opcoes_sistema')
    op.drop_table('opcoes_sistema')
    # ### end Alembic commands ###
