"""create_configuracoes_table

Revision ID: 18ac05771430
Revises: de3c51351108
Create Date: 2026-07-16 13:45:45.657795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ac05771430'
down_revision: Union[str, Sequence[str], None] = 'de3c51351108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('smtp_from', sa.String(length=255), nullable=True),
    sa.Column('ti_destination_email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracoes_id'), 'configuracoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracoes_id'), table_name='configuracoes')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
