"""Initial migration

Revision ID: 972d8cee28f0
Revises: 
Create Date: 2026-07-03 13:29:50.225141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972d8cee28f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.Enum('CLIENTE', 'TECNICO', 'SUPERVISOR', 'GERENTE', name='userprofile'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_technician_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ABERTO', 'EM_ATENDIMENTO', 'AGUARDANDO_PECA', 'RESOLVIDO', 'FECHADO', 'REABERTO', name='ticketstatus'), nullable=False),
    sa.Column('location_type', sa.Enum('QUARTO', 'AREA_COMUM', name='locationtype'), nullable=False),
    sa.Column('location_details', sa.String(length=150), nullable=False),
    sa.Column('is_room_occupied', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('sla_duration_hours', sa.Float(), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('sla_frozen_start', sa.DateTime(), nullable=True),
    sa.Column('sla_paused_seconds', sa.Integer(), nullable=False),
    sa.Column('reopen_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamados_code'), 'chamados', ['code'], unique=True)
    op.create_index(op.f('ix_chamados_id'), 'chamados', ['id'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['chamados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_id'), 'comentarios', ['id'], unique=False)
    op.create_table('logs_notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['chamados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_notificacao_id'), 'logs_notificacao', ['id'], unique=False)
    op.create_table('logs_transferencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('transferred_by_id', sa.Integer(), nullable=False),
    sa.Column('source_technician_id', sa.Integer(), nullable=True),
    sa.Column('target_technician_id', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_technician_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['target_technician_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['chamados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transferred_by_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_transferencia_id'), 'logs_transferencia', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_transferencia_id'), table_name='logs_transferencia')
    op.drop_table('logs_transferencia')
    op.drop_index(op.f('ix_logs_notificacao_id'), table_name='logs_notificacao')
    op.drop_table('logs_notificacao')
    op.drop_index(op.f('ix_comentarios_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_chamados_id'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_code'), table_name='chamados')
    op.drop_table('chamados')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
