"""migrate_smtp_to_user

Revision ID: d27f91f13990
Revises: 18ac05771430
Create Date: 2026-07-16 14:10:23.402539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27f91f13990'
down_revision: Union[str, Sequence[str], None] = '18ac05771430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracoes_id'), table_name='configuracoes')
    op.drop_table('configuracoes')
    op.add_column('usuarios', sa.Column('smtp_host', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('smtp_user', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('smtp_password', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('smtp_from', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('ti_destination_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'ti_destination_email')
    op.drop_column('usuarios', 'smtp_from')
    op.drop_column('usuarios', 'smtp_password')
    op.drop_column('usuarios', 'smtp_user')
    op.drop_column('usuarios', 'smtp_port')
    op.drop_column('usuarios', 'smtp_host')
    op.create_table('configuracoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('smtp_host', sa.VARCHAR(length=255), nullable=True),
    sa.Column('smtp_port', sa.INTEGER(), nullable=True),
    sa.Column('smtp_user', sa.VARCHAR(length=255), nullable=True),
    sa.Column('smtp_password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('smtp_from', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ti_destination_email', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracoes_id'), 'configuracoes', ['id'], unique=False)
    # ### end Alembic commands ###
