"""Add Priority and Destination Queue

Revision ID: de3c51351108
Revises: 972d8cee28f0
Create Date: 2026-07-07 15:55:05.136974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3c51351108'
down_revision: Union[str, Sequence[str], None] = '972d8cee28f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chamados', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('chamados', sa.Column('destination_queue', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chamados', 'destination_queue')
    op.drop_column('chamados', 'priority')
    # ### end Alembic commands ###
